//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedMillTotalRecievable
    {
        public int feedmillid { get; set; }
        public decimal totalPriceRecievable { get; set; }
        public decimal totalPayable { get; set; }
    }
}
