//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HCSMLEntities1 : DbContext
    {
        public HCSMLEntities1()
            : base("name=HCSMLEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<bankuser> bankusers { get; set; }
        public virtual DbSet<companyuser> companyusers { get; set; }
        public virtual DbSet<FeedMillTotalRecievable> FeedMillTotalRecievables { get; set; }
        public virtual DbSet<feedmilluser> feedmillusers { get; set; }
        public virtual DbSet<individualuser> individualusers { get; set; }
        public virtual DbSet<Khata> Khatas { get; set; }
        public virtual DbSet<KhataTypeCode> KhataTypeCodes { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<OtherKhata> OtherKhatas { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<producttype> producttypes { get; set; }
        public virtual DbSet<purchaseproduct> purchaseproducts { get; set; }
        public virtual DbSet<purchaseruser> purchaserusers { get; set; }
        public virtual DbSet<saleproduct> saleproducts { get; set; }
        public virtual DbSet<saletype> saletypes { get; set; }
        public virtual DbSet<SellerTotalPayable> SellerTotalPayables { get; set; }
        public virtual DbSet<sellertype> sellertypes { get; set; }
    }
}
