//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherKhata
    {
        public int id { get; set; }
        public decimal payable_naam { get; set; }
        public decimal receivable_jama { get; set; }
        public string productname { get; set; }
        public decimal weight { get; set; }
        public System.DateTime date { get; set; }
        public string khatatypecde { get; set; }
        public decimal totalreceivable_jama { get; set; }
        public decimal totalpayable_naam { get; set; }
        public int sellerid { get; set; }
        public int purchaserid { get; set; }
        public string activitycode { get; set; }
        public string sellertypecode { get; set; }
        public string purchasertypecode { get; set; }
        public int purchaseproductid { get; set; }
        public int saleproductid { get; set; }
    }
}
