//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class producttype
    {
        public producttype()
        {
            this.products = new HashSet<product>();
        }
    
        public string product_type_cde { get; set; }
        public string product_type_dsc { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
