//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseruser
    {
        public int purchaserid { get; set; }
        public string purchasername_e { get; set; }
        public string mobile { get; set; }
        public string phone { get; set; }
        public string address_e { get; set; }
        public string email { get; set; }
        public string imagepath { get; set; }
        public byte[] imagetobyte { get; set; }
        public System.DateTime date { get; set; }
        public string purchasername_u { get; set; }
        public string address_u { get; set; }
        public string bankaccountnumber { get; set; }
        public string bankbranch_e { get; set; }
        public string bankbranch_u { get; set; }
    }
}
