//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class saletype
    {
        public string saletypecde { get; set; }
        public string saletype_e { get; set; }
        public string saletype_u { get; set; }
    }
}
