//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class saleproduct
    {
        public int seqid { get; set; }
        public int productid { get; set; }
        public System.DateTime date { get; set; }
        public int feedmillid { get; set; }
        public decimal rate { get; set; }
        public string drivernumber { get; set; }
        public string vehicleno { get; set; }
        public decimal price { get; set; }
        public decimal recievableprice { get; set; }
        public decimal labour { get; set; }
        public decimal totalpricerecieveable { get; set; }
        public decimal amountrecieved { get; set; }
        public string productname { get; set; }
        public int noofbags { get; set; }
        public decimal bagweight { get; set; }
        public decimal extraweight { get; set; }
        public decimal weight { get; set; }
        public decimal totalpayable { get; set; }
        public decimal fee { get; set; }
        public decimal thread { get; set; }
        public decimal accountcharges { get; set; }
        public decimal bardana { get; set; }
        public decimal commissionpercent { get; set; }
        public decimal commissionamount { get; set; }
        public string purchasertypecde { get; set; }
        public string purchasername { get; set; }
        public string saletypecde { get; set; }
        public string vehiclerent { get; set; }
        public string sellertypecde { get; set; }
        public string sellername { get; set; }
    }
}
