//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerTotalPayable
    {
        public string seller_cde { get; set; }
        public int sellerid { get; set; }
        public decimal totalpayable { get; set; }
        public decimal totalreceivable { get; set; }
    }
}
