//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class sellertype
    {
        public sellertype()
        {
            this.purchaseproducts = new HashSet<purchaseproduct>();
        }
    
        public string seller_cde { get; set; }
        public string seller_des_e { get; set; }
        public string seller_des_u { get; set; }
    
        public virtual ICollection<purchaseproduct> purchaseproducts { get; set; }
    }
}
